### ISSUE TITLE
Load Error under Ruby 2.7.6

### ISSUE THREAD

**Issue by noctivityinc** [SleeplessByte/expo-server-sdk-ruby#10]
Im trying to use the gem in Rails 5.2 under Ruby 2.7.6 and get this:

```
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
Traceback (most recent call last):
	33: from bin/rails:3:in `<main>'
	32: from bin/rails:3:in `load'
	31: from /Users/jlippiner/Projects/wecora/five/bin/spring:15:in `<top (required)>'
	30: from /Users/jlippiner/Projects/wecora/five/bin/spring:15:in `require'
	29: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
	28: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
	27: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
	26: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
	25: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
	24: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
	23: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
	22: from /Users/jlippiner/Projects/wecora/five/bin/rails:9:in `<top (required)>'
	21: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	20: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	19: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/commands.rb:18:in `<main>'
	18: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/command.rb:46:in `invoke'
	17: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/command/base.rb:69:in `perform'
	16: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	15: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	14: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	13: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	12: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:142:in `tap'
	11: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	10: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 9: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 8: from /Users/jlippiner/Projects/wecora/five/config/application.rb:13:in `<main>'
	 7: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bundler-2.2.33/lib/bundler.rb:175:in `require'
	 6: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bundler-2.2.33/lib/bundler/runtime.rb:44:in `require'
	 5: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bundler-2.2.33/lib/bundler/runtime.rb:44:in `each'
	 4: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bundler-2.2.33/lib/bundler/runtime.rb:55:in `block in require'
	 3: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bundler-2.2.33/lib/bundler/runtime.rb:55:in `each'
	 2: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bundler-2.2.33/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	 1: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
/Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- expo-server-sdk (LoadError)
	57: from bin/rails:3:in `<main>'
	56: from bin/rails:3:in `load'
	55: from /Users/jlippiner/Projects/wecora/five/bin/spring:15:in `<top (required)>'
	54: from /Users/jlippiner/Projects/wecora/five/bin/spring:15:in `require'
	53: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
	52: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
	51: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
	50: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
	49: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
	48: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
	47: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
	46: from /Users/jlippiner/Projects/wecora/five/bin/rails:9:in `<top (required)>'
	45: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	44: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	43: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/commands.rb:18:in `<main>'
	42: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/command.rb:46:in `invoke'
	41: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/command/base.rb:69:in `perform'
	40: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	39: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	38: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	37: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	36: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:142:in `tap'
	35: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/railties-5.2.8.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	34: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	33: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	32: from /Users/jlippiner/Projects/wecora/five/config/application.rb:13:in `<main>'
	31: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bundler-2.2.33/lib/bundler.rb:175:in `require'
	30: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bundler-2.2.33/lib/bundler/runtime.rb:44:in `require'
	29: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bundler-2.2.33/lib/bundler/runtime.rb:44:in `each'
	28: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bundler-2.2.33/lib/bundler/runtime.rb:51:in `block in require'
	27: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bundler-2.2.33/lib/bundler/runtime.rb:73:in `rescue in block in require'
	26: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	25: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	24: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/expo-server-sdk-0.1.6/lib/expo/server/sdk.rb:4:in `<main>'
	23: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/expo-server-sdk-0.1.6/lib/expo/server/sdk.rb:4:in `require_relative'
	22: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/expo-server-sdk-0.1.6/lib/push/client.rb:4:in `<main>'
	21: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	20: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	19: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	18: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	17: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	16: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/http-5.2.0/lib/http.rb:16:in `<main>'
	15: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	14: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	13: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	12: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	11: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	10: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/http-5.2.0/lib/http/response/parser.rb:3:in `<main>'
	 9: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
	 8: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	 7: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
	 6: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 5: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 4: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/llhttp-ffi-0.5.0/lib/llhttp.rb:6:in `<main>'
	 3: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/llhttp-ffi-0.5.0/lib/llhttp.rb:13:in `<module:LLHttp>'
	 2: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `ffi_lib'
	 1: from /Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `map'
/Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/llhttp-ffi-0.5.0/ext/aarch64-darwin/libllhttp-ext.bundle': dlopen(/Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/llhttp-ffi-0.5.0/ext/aarch64-darwin/libllhttp-ext.bundle, 0x0005): tried: '/Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/llhttp-ffi-0.5.0/ext/aarch64-darwin/libllhttp-ext.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/llhttp-ffi-0.5.0/ext/aarch64-darwin/libllhttp-ext.bundle' (no such file), '/Users/jlippiner/.rvm/gems/ruby-2.7.6@wecora_rails_5/gems/llhttp-ffi-0.5.0/ext/aarch64-darwin/libllhttp-ext.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')) (LoadError)
```

Which prevents the server from starting

**Comment by SleeplessByte** [comment]
It seems that you're trying to load `expo-server-sdk`, instead of `expo/server/sdk`, as listed in [the Readme](https://github.com/SleeplessByte/expo-server-sdk-ruby?tab=readme-ov-file#usage).

If you're _not_ manually requiring this gem you can try to add `require: false` in your Gemfile, and then manually requiring it. From the stacktrace I see a mention of Rails 5. Zeitwerk is loading this correctly from Rails 6 onwards.
